//
// Generated by JTB 1.2.2
//

package de.uniluebeck.ifis.anf.dbsystem.parser.syntaxtree;

/**
 * The interface which all syntax tree classes must implement.
 */
public interface Node extends java.io.Serializable {
   public void accept(de.uniluebeck.ifis.anf.dbsystem.parser.visitor.Visitor v);
   public Object accept(de.uniluebeck.ifis.anf.dbsystem.parser.visitor.ObjectVisitor v, Object argu);

   // It is the responsibility of each implementing class to call
   // setParent() on each of its child Nodes.
   public void setParent(Node n);
   public Node getParent();
}

